### ISSUE TITLE
Postgres installation failure

### ISSUE THREAD

**Issue by panoel** [neonevm/infrastructure-kubernetes#5]
In file postgres/values.yaml, line 39 should be changed to "storageClassName" so that it matches the postgres/templates/efs-csi-driver.yaml checks on lines 2 and 15.
Otherwise, one can get the following error:
```
Error: template: postgres/templates/efs-csi-driver.yaml:2:7: executing "postgres/templates/efs-csi-driver.yaml" at <eq .Values.persistence.storageClassName "efs">: error calling eq: incompatible types for comparison
```

**Comment by thespamer** [comment]
thanks, we are moving developmento to main branch where this issue has been fixed.

Regards,
Juliano
